# Generated by Django 5.2.3 on 2026-06-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Single Room"', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL slug, e.g. "single_room"', unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in dropdowns')),
            ],
            options={
                'verbose_name': 'House Type',
                'verbose_name_plural': 'House Types',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
