# Generated by Django 5.2.3 on 2026-06-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_inquiry_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Furnished 1BR in Kilimani', max_length=200)),
                ('description', models.TextField()),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('estate', models.CharField(blank=True, max_length=200)),
                ('house_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('studio', 'Studio'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('four_bedroom', 'Four Bedroom+'), ('townhouse', 'Townhouse'), ('villa', 'Villa')], default='one_bedroom', max_length=30)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in KES', max_digits=10)),
                ('contact_name', models.CharField(blank=True, help_text='Landlord or agent name', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='admin_listings/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Listing',
                'ordering': ['-created_at'],
            },
        ),
    ]
