# Generated by Django 5.2.3 on 2026-06-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_adminlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='admin_listings/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.adminlisting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
