# Generated by Django 5.2.3 on 2026-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction reference (M-Pesa code or receipt)', max_length=100),
        ),
    ]
