# Generated by Django 5.2.3 on 2026-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rentpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=10),
        ),
    ]
