# Generated by Django 5.2.3 on 2026-06-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_mpesatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_due_day', models.IntegerField(default=5)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('terms', models.TextField(blank=True)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('landlord_accepted', models.BooleanField(default=False)),
                ('landlord_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_accepted', models.BooleanField(default=False)),
                ('tenant_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
