# Generated by Django 5.2.3 on 2026-06-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_utilitybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='utility_bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payment', to='tenants.utilitybill'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('utility', 'Utility'), ('other', 'Other')], default='mpesa', max_length=10),
        ),
    ]
