# Generated by Django 5.2.3 on 2026-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_rentpayment_utility_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit for this bill', max_digits=10, null=True),
        ),
    ]
