# Generated by Django 5.2.3 on 2026-06-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_utilitybill_rate_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='reading',
        ),
    ]
