# Generated by Django 5.2.3 on 2026-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_b2ctransaction_result_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ctransaction',
            name='b2c_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='B2C charges paid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='completed_at',
            field=models.CharField(blank=True, help_text='Transaction completed date/time from callback', max_length=50),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='receiver_public_name',
            field=models.CharField(blank=True, help_text='Recipient name from callback', max_length=200),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='transaction_receipt',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number (from callback result)', max_length=100),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Safaricom B2C transaction ID (from request response)', max_length=100),
        ),
    ]
