# Generated by Django 5.2.3 on 2026-06-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('house_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('four_bedroom', 'Four Bedroom'), ('studio', 'Studio')], max_length=20)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='unit_images/')),
                ('image_2', models.ImageField(blank=True, upload_to='unit_images/')),
                ('image_3', models.ImageField(blank=True, upload_to='unit_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='units.unit')),
            ],
        ),
    ]
