# Generated by Django 5.2.3 on 2026-06-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_per_unit', models.DecimalField(decimal_places=2, default=50.0, help_text='Monthly platform fee per unit (KES)', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
            },
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee = unit_count × fee_per_unit at time of creation', max_digits=10),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='unit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landlordsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.subscriptionplan'),
        ),
    ]
