# Generated by Django 5.2.3 on 2026-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_platformconfig_landlordsubscription_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee_per_unit',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Monthly platform fee per unit for this landlord (KES). Set 0 for free.', max_digits=8),
        ),
    ]
