# Generated by Django 5.2.3 on 2026-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_fee_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Free trial duration in days'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial started', null=True),
        ),
    ]
