# Generated by Django 5.2.3 on 2026-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platformconfig_trial_days_profile_trial_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='callback_url',
            field=models.CharField(blank=True, help_text='Override M-Pesa callback URL (e.g., ngrok URL). Leave blank to use MPESA_CALLBACK_URL from settings.', max_length=500),
        ),
    ]
