# Generated by Django 5.2.3 on 2026-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platformconfig_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, help_text='Override M-Pesa Consumer Key. Leave blank to use settings.', max_length=200),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, help_text='Override M-Pesa Consumer Secret. Leave blank to use settings.', max_length=200),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mpesa_env',
            field=models.CharField(blank=True, help_text='Override M-Pesa environment (sandbox/production). Leave blank to use settings.', max_length=20),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mpesa_passkey',
            field=models.CharField(blank=True, help_text='Override M-Pesa Passkey. Leave blank to use settings.', max_length=200),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Override M-Pesa Shortcode. Leave blank to use settings.', max_length=20),
        ),
    ]
