# Generated by Django 5.2.3 on 2026-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_platformconfig_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, help_text='Your M-Pesa Consumer Key (Daraja API)', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, help_text='Your M-Pesa Consumer Secret', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='mpesa_passkey',
            field=models.CharField(blank=True, help_text='Your M-Pesa Passkey', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Your M-Pesa Shortcode / Paybill', max_length=20),
        ),
    ]
