# Generated by Django 5.2.3 on 2026-06-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfig',
            name='mpesa_consumer_key',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='mpesa_consumer_secret',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='mpesa_env',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='mpesa_passkey',
        ),
        migrations.RemoveField(
            model_name='platformconfig',
            name='mpesa_shortcode',
        ),
    ]
