# Generated by Django 5.2.3 on 2026-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_platformconfig_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mpesa_callback_url',
            field=models.CharField(blank=True, help_text='Override M-Pesa callback URL (e.g., ngrok URL) for this landlord', max_length=500),
        ),
    ]
