# Generated by Django 5.2.3 on 2026-06-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_mpesa_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='c2b_confirmation_url',
            field=models.CharField(blank=True, help_text='C2B Confirmation URL (public URL M-Pesa will call). Falls back to domain + /mpesa/c2b/confirmation/', max_length=500),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='c2b_registered',
            field=models.BooleanField(default=False, help_text='Whether C2B URLs have been registered with Safaricom'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='c2b_validation_url',
            field=models.CharField(blank=True, help_text='C2B Validation URL (public URL M-Pesa will call). Falls back to domain + /mpesa/c2b/validation/', max_length=500),
        ),
    ]
