# Generated by Django 5.2.3 on 2026-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_platformconfig_c2b_confirmation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c2b_registered',
            field=models.BooleanField(default=False, help_text='Whether C2B URLs are registered for this landlord'),
        ),
    ]
