# Generated by Django 5.2.3 on 2026-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_c2b_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c2b_confirmation_url',
            field=models.CharField(blank=True, help_text='C2B Confirmation URL (public URL M-Pesa will call). Leave blank to auto-derive.', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='c2b_validation_url',
            field=models.CharField(blank=True, help_text='C2B Validation URL (public URL M-Pesa will call). Leave blank to auto-derive.', max_length=500),
        ),
    ]
