# Generated by Django 5.2.3 on 2026-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_c2b_confirmation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c2b_shortcode',
            field=models.CharField(blank=True, help_text='Your C2B Paybill number (for receiving M-Pesa payments). Different from STK Push shortcode.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Your M-Pesa Shortcode / Paybill (for STK Push)', max_length=20),
        ),
    ]
