# Generated by Django 5.2.3 on 2026-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_c2b_shortcode_alter_profile_mpesa_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b2c_initiator_name',
            field=models.CharField(blank=True, help_text='B2C API initiator username (set up in your paybill)', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='b2c_initiator_password',
            field=models.CharField(blank=True, help_text='B2C API initiator password', max_length=200),
        ),
    ]
