# Generated by Django 5.2.3 on 2026-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_b2c_initiator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b2c_shortcode',
            field=models.CharField(blank=True, help_text='B2C Party A — your paybill that sends commission payments', max_length=20),
        ),
    ]
