# Generated by Django 5.2.3 on 2026-06-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_b2c_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b2c_callback_base_url',
            field=models.CharField(blank=True, help_text='Public URL base for B2C callbacks (e.g. https://yourdomain.com). Leave blank to use C2B confirmation URL.', max_length=500),
        ),
    ]
