# Generated by Django 4.2.19 on 2026-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_b2c_callback_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number — used as unique identifier for M-Pesa payments', max_length=20, null=True, unique=True),
        ),
    ]
