# Generated by Django 5.2.3 on 2026-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per unit of electricity', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='trash_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat rate for trash collection', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='water_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per unit of water', max_digits=10),
        ),
    ]
